# Generated by Django 3.1.7 on 2022-03-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_videomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(upload_to=None),
        ),
    ]
